# These year settings make use of old JSON files. If you download a new JSON
# API response, then you may need to adjust settings (more toward current year).
[[years]]
# Years between this year and the first year with JSON fields are only read from
# CSV files which need to have "pos <year>" columns.
year = 2014

[[years]]
year = 2019
json = {artist="a", title="s", pos="pos", prv="prv", year="yr", old=true, rows=["data", 0]}

[[years]]
year = 2020
json = {artist="a", title="s", pos="pos", prv="prv", year="yr", old=true, rows=["data", 0]}
csv = {artist="ARTIEST", title="TITEL", pos="NR.", year="JAAR"}

[[years]]
year = 2021
json = {old=true, rows=["positions"]}
csv.encoding = "windows-1252"

[[years]]
year = 2022
csv.encoding = "windows-1252"
json.rows = ["positions"]

[[years]]
year = 2023
json.skip = true # Because Pink Floyd - Breathe is overwritten in old JSON files
json.rows = ["positions"]

[[years]]
year = 2023.5
csv.offset = 2000
csv.name = "De-Extra-500-2023.csv"
json.name = "de-extra-500-van-2023-12-11.json"
json.rows = ["positions"]

[[years]]
year = 2024
csv = {artist="Artiest", title="Titel", pos="Notering", year="Jaartal"}
json.rows = ["positions"]

[[years]]
year = 2025
csv = {artist="Artiest", title="Titel", pos="Notering", year="Jaartal", name="TOP2000-2025.csv", skip=1}
json.rows = ["positions"]

[wiki]
api = "https://nl.wikipedia.org/w/api.php"
path = "/wiki/"
page = "Lijst_van_Radio_2-Top_2000's"
oldid = 70350713
artist = "Artiest"
title = "Titel"
year = "Jaar"
